# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests.js

on:
  push:
    branches: [ main, next, 1.x ]
  pull_request:
    branches: [ main, next, 1.x ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: 13
    - name: Yarn
      run: yarn
    - name: Lint
      run: yarn ci:lint
    - name: Test units
      run: yarn test:unit
    - name: Codecov
      uses: codecov/codecov-action@v1.0.7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

